//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LdapSso.Modules.LdapSsoClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResult", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum AuthenticationResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_CREDENTIALS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_DOES_NOT_EXISTS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOWN = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGroupDto", Namespace="http://schemas.datacontract.org/2004/07/LdapSso.Services.Dtos")]
    [System.SerializableAttribute()]
    public partial class UserGroupDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GroupNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] GroupNames {
            get {
                return this.GroupNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNamesField, value) != true)) {
                    this.GroupNamesField = value;
                    this.RaisePropertyChanged("GroupNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LdapSsoClient.ILdapSsoService")]
    public interface ILdapSsoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapSsoService/AuthenticateUser", ReplyAction="http://tempuri.org/ILdapSsoService/AuthenticateUserResponse")]
        LdapSso.Modules.LdapSsoClient.AuthenticationResult AuthenticateUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapSsoService/AuthenticateUser", ReplyAction="http://tempuri.org/ILdapSsoService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<LdapSso.Modules.LdapSsoClient.AuthenticationResult> AuthenticateUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapSsoService/GetUserGroups", ReplyAction="http://tempuri.org/ILdapSsoService/GetUserGroupsResponse")]
        LdapSso.Modules.LdapSsoClient.UserGroupDto GetUserGroups(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapSsoService/GetUserGroups", ReplyAction="http://tempuri.org/ILdapSsoService/GetUserGroupsResponse")]
        System.Threading.Tasks.Task<LdapSso.Modules.LdapSsoClient.UserGroupDto> GetUserGroupsAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILdapSsoServiceChannel : LdapSso.Modules.LdapSsoClient.ILdapSsoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LdapSsoServiceClient : System.ServiceModel.ClientBase<LdapSso.Modules.LdapSsoClient.ILdapSsoService>, LdapSso.Modules.LdapSsoClient.ILdapSsoService {
        
        public LdapSsoServiceClient() {
        }
        
        public LdapSsoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LdapSsoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LdapSsoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LdapSsoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LdapSso.Modules.LdapSsoClient.AuthenticationResult AuthenticateUser(string username, string password) {
            return base.Channel.AuthenticateUser(username, password);
        }
        
        public System.Threading.Tasks.Task<LdapSso.Modules.LdapSsoClient.AuthenticationResult> AuthenticateUserAsync(string username, string password) {
            return base.Channel.AuthenticateUserAsync(username, password);
        }
        
        public LdapSso.Modules.LdapSsoClient.UserGroupDto GetUserGroups(string username) {
            return base.Channel.GetUserGroups(username);
        }
        
        public System.Threading.Tasks.Task<LdapSso.Modules.LdapSsoClient.UserGroupDto> GetUserGroupsAsync(string username) {
            return base.Channel.GetUserGroupsAsync(username);
        }
    }
}
