//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LdapSso.Web.LdapSsoClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LdapSsoClient.ILdapSsoService")]
    public interface ILdapSsoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapSsoService/AuthenticateUser", ReplyAction="http://tempuri.org/ILdapSsoService/AuthenticateUserResponse")]
        AuthenticationResult AuthenticateUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapSsoService/AuthenticateUser", ReplyAction="http://tempuri.org/ILdapSsoService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<AuthenticationResult> AuthenticateUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapSsoService/AuthenticateUserLdap", ReplyAction="http://tempuri.org/ILdapSsoService/AuthenticateUserLdapResponse")]
        bool AuthenticateUserLdap(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapSsoService/AuthenticateUserLdap", ReplyAction="http://tempuri.org/ILdapSsoService/AuthenticateUserLdapResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateUserLdapAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILdapSsoServiceChannel : LdapSso.Web.LdapSsoClient.ILdapSsoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LdapSsoServiceClient : System.ServiceModel.ClientBase<LdapSso.Web.LdapSsoClient.ILdapSsoService>, LdapSso.Web.LdapSsoClient.ILdapSsoService {
        
        public LdapSsoServiceClient() {
        }
        
        public LdapSsoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LdapSsoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LdapSsoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LdapSsoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AuthenticationResult AuthenticateUser(string username, string password) {
            return base.Channel.AuthenticateUser(username, password);
        }
        
        public System.Threading.Tasks.Task<AuthenticationResult> AuthenticateUserAsync(string username, string password) {
            return base.Channel.AuthenticateUserAsync(username, password);
        }
        
        public bool AuthenticateUserLdap(string username, string password) {
            return base.Channel.AuthenticateUserLdap(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateUserLdapAsync(string username, string password) {
            return base.Channel.AuthenticateUserLdapAsync(username, password);
        }
    }
}
